name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  var1: $(dave1)
jobs:
- job: One
strategy:
matrix:
      Python35:
        PYTHON_VERSION: '3.5'
      Python36:
        PYTHON_VERSION: '3.6'
  steps:
  - script: echo First step! Job1 $(var1)

- job: Two
  steps:
  - script: echo First step! Job2 $(var1)
