pool:
  vmImage: 'Ubuntu-16.04'
name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  var1: $(dave1)
jobs:
- job: One
  steps:
  - script: echo First step! Job1 $(var1)

- job: Two
  steps:
  - script: echo First step! Job2 $(var1)
